// <auto-generated />
using System;
using HotelManageSys.API.Models.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelManageSys.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AmenityRoom", b =>
                {
                    b.Property<int>("AmenitiesAmenityId")
                        .HasColumnType("int");

                    b.Property<int>("RoomsRoomId")
                        .HasColumnType("int");

                    b.HasKey("AmenitiesAmenityId", "RoomsRoomId");

                    b.HasIndex("RoomsRoomId");

                    b.ToTable("AmenityRoom");
                });

            modelBuilder.Entity("HotelManageSys.API.Models.AdditionalOffer", b =>
                {
                    b.Property<int>("AdditionalOfferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdditionalOfferId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AdditionalOfferId");

                    b.ToTable("AdditionalOffers");

                    b.HasData(
                        new
                        {
                            AdditionalOfferId = 1,
                            IsActive = true,
                            Name = "Śniadanie (Bufet)",
                            Price = 45m
                        },
                        new
                        {
                            AdditionalOfferId = 2,
                            IsActive = true,
                            Name = "Miejsce parkingowe",
                            Price = 30m
                        },
                        new
                        {
                            AdditionalOfferId = 3,
                            IsActive = true,
                            Name = "Szampan",
                            Price = 150m
                        },
                        new
                        {
                            AdditionalOfferId = 4,
                            IsActive = true,
                            Name = "Przedłużone wymeldowanie",
                            Price = 100m
                        });
                });

            modelBuilder.Entity("HotelManageSys.API.Models.Amenity", b =>
                {
                    b.Property<int>("AmenityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AmenityId"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("AmenityId");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            AmenityId = 1,
                            Description = "Darmowy szybki internet",
                            IsActive = true,
                            Name = "WiFi"
                        },
                        new
                        {
                            AmenityId = 2,
                            Description = "Klimatyzacja sterowana z pokoju",
                            IsActive = true,
                            Name = "Klimatyzacja"
                        },
                        new
                        {
                            AmenityId = 3,
                            Description = "Kibel",
                            IsActive = true,
                            Name = "Kibel"
                        },
                        new
                        {
                            AmenityId = 4,
                            Description = "Schłodzone napoje",
                            IsActive = true,
                            Name = "Minibar"
                        });
                });

            modelBuilder.Entity("HotelManageSys.API.Models.Guest", b =>
                {
                    b.Property<int>("GuestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GuestId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdentityCardNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("GuestId");

                    b.ToTable("Guests");

                    b.HasData(
                        new
                        {
                            GuestId = 1,
                            Email = "pudzian@test.pl",
                            FirstName = "Mariusz",
                            IdentityCardNumber = "ID123",
                            IsActive = true,
                            LastName = "Pudzianowski",
                            PhoneNumber = "123567345"
                        },
                        new
                        {
                            GuestId = 2,
                            Email = "robert@lewy.pl",
                            FirstName = "Robert",
                            IdentityCardNumber = "PASS987",
                            IsActive = true,
                            LastName = "Lewandowski",
                            PhoneNumber = "987654321"
                        },
                        new
                        {
                            GuestId = 3,
                            Email = "iga@tennis.pl",
                            FirstName = "Iga",
                            IdentityCardNumber = "ID456",
                            IsActive = true,
                            LastName = "Świątek",
                            PhoneNumber = "555666777"
                        });
                });

            modelBuilder.Entity("HotelManageSys.API.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PaymentId");

                    b.HasIndex("ReservationId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentId = 1,
                            IsActive = true,
                            PaymentDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "CARD",
                            PaymentStatus = "PAID",
                            Price = 820m,
                            ReservationId = 1,
                            Title = "Opłata za pobyt (ID: 1)"
                        },
                        new
                        {
                            PaymentId = 2,
                            IsActive = true,
                            PaymentDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "MONEY",
                            PaymentStatus = "PAID",
                            Price = 200m,
                            ReservationId = 2,
                            Title = "Zaliczka rezerwacyjna"
                        },
                        new
                        {
                            PaymentId = 3,
                            IsActive = true,
                            PaymentDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "TRANSFER",
                            PaymentStatus = "PENDING",
                            Price = 2800m,
                            ReservationId = 3,
                            Title = "Pełna opłata"
                        });
                });

            modelBuilder.Entity("HotelManageSys.API.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuestId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReservationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("ReservationId");

                    b.HasIndex("GuestId");

                    b.HasIndex("RoomId");

                    b.HasIndex("WorkerId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            ReservationId = 1,
                            CheckInDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 1,
                            IsActive = true,
                            Notes = "Jakieś tam uwagi",
                            ReservationDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReservationStatus = "COMPLETED",
                            RoomId = 4,
                            TotalPrice = 820m,
                            WorkerId = 1
                        },
                        new
                        {
                            ReservationId = 2,
                            CheckInDate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 2,
                            IsActive = true,
                            Notes = "Testowa notatka",
                            ReservationDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReservationStatus = "CONFIRMED",
                            RoomId = 2,
                            TotalPrice = 945m,
                            WorkerId = 2
                        },
                        new
                        {
                            ReservationId = 3,
                            CheckInDate = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2024, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 3,
                            IsActive = true,
                            Notes = "VIP",
                            ReservationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReservationStatus = "PENDING",
                            RoomId = 6,
                            TotalPrice = 2800m,
                            WorkerId = 2
                        });
                });

            modelBuilder.Entity("HotelManageSys.API.Models.ReservationAdditionalOffer", b =>
                {
                    b.Property<int>("ReservationAdditionalOfferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationAdditionalOfferId"));

                    b.Property<int>("AdditionalOfferId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("OfferPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.HasKey("ReservationAdditionalOfferId");

                    b.HasIndex("AdditionalOfferId");

                    b.HasIndex("ReservationId");

                    b.ToTable("ReservationAdditionalOffers");

                    b.HasData(
                        new
                        {
                            ReservationAdditionalOfferId = 1,
                            AdditionalOfferId = 1,
                            IsActive = true,
                            Notes = "",
                            OfferPrice = 45m,
                            Quantity = 2,
                            ReservationId = 1
                        },
                        new
                        {
                            ReservationAdditionalOfferId = 2,
                            AdditionalOfferId = 2,
                            IsActive = true,
                            Notes = "Nr rej. WA12345",
                            OfferPrice = 30m,
                            Quantity = 1,
                            ReservationId = 1
                        },
                        new
                        {
                            ReservationAdditionalOfferId = 3,
                            AdditionalOfferId = 1,
                            IsActive = true,
                            Notes = "",
                            OfferPrice = 45m,
                            Quantity = 1,
                            ReservationId = 2
                        });
                });

            modelBuilder.Entity("HotelManageSys.API.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            Floor = 1,
                            IsActive = true,
                            Number = "101",
                            RoomTypeId = 1,
                            Status = "AVAILABLE"
                        },
                        new
                        {
                            RoomId = 2,
                            Floor = 1,
                            IsActive = true,
                            Number = "102",
                            RoomTypeId = 1,
                            Status = "OCCUPIED"
                        },
                        new
                        {
                            RoomId = 3,
                            Floor = 1,
                            IsActive = true,
                            Number = "103",
                            RoomTypeId = 4,
                            Status = "OCCUPIED"
                        },
                        new
                        {
                            RoomId = 4,
                            Floor = 2,
                            IsActive = true,
                            Number = "201",
                            RoomTypeId = 2,
                            Status = "AVAILABLE"
                        },
                        new
                        {
                            RoomId = 5,
                            Floor = 2,
                            IsActive = true,
                            Number = "202",
                            RoomTypeId = 2,
                            Status = "AVAILABLE"
                        },
                        new
                        {
                            RoomId = 6,
                            Floor = 3,
                            IsActive = true,
                            Number = "301",
                            RoomTypeId = 3,
                            Status = "AVAILABLE"
                        });
                });

            modelBuilder.Entity("HotelManageSys.API.Models.RoomType", b =>
                {
                    b.Property<int>("RoomTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomTypeId"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("RoomTypeId");

                    b.ToTable("RoomTypes");

                    b.HasData(
                        new
                        {
                            RoomTypeId = 1,
                            BasePrice = 180m,
                            Description = "Wygodny pokój standardowy 1-2 os.",
                            IsActive = true,
                            Name = "Standard"
                        },
                        new
                        {
                            RoomTypeId = 2,
                            BasePrice = 350m,
                            Description = "Pokój o podwyższonym standardzie z widokiem",
                            IsActive = true,
                            Name = "Deluxe"
                        },
                        new
                        {
                            RoomTypeId = 3,
                            BasePrice = 700m,
                            Description = "Przestronny apartament z aneksem kuchennym",
                            IsActive = true,
                            Name = "Apartament VIP"
                        },
                        new
                        {
                            RoomTypeId = 4,
                            BasePrice = 450m,
                            Description = "Idealny pokój dla rodziny 2+2",
                            IsActive = true,
                            Name = "Rodzinny"
                        });
                });

            modelBuilder.Entity("HotelManageSys.API.Models.Worker", b =>
                {
                    b.Property<int>("WorkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkerId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WorkerId");

                    b.ToTable("Workers");

                    b.HasData(
                        new
                        {
                            WorkerId = 1,
                            FirstName = "Adam",
                            IsActive = true,
                            LastName = "Kowalski",
                            Login = "admin",
                            Password = "admin123",
                            Role = "ADMIN"
                        },
                        new
                        {
                            WorkerId = 2,
                            FirstName = "Anna",
                            IsActive = true,
                            LastName = "Nowak",
                            Login = "anowak",
                            Password = "user123",
                            Role = "WORKER"
                        });
                });

            modelBuilder.Entity("AmenityRoom", b =>
                {
                    b.HasOne("HotelManageSys.API.Models.Amenity", null)
                        .WithMany()
                        .HasForeignKey("AmenitiesAmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelManageSys.API.Models.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomsRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelManageSys.API.Models.Payment", b =>
                {
                    b.HasOne("HotelManageSys.API.Models.Reservation", "Reservation")
                        .WithMany("Payments")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("HotelManageSys.API.Models.Reservation", b =>
                {
                    b.HasOne("HotelManageSys.API.Models.Guest", "Guest")
                        .WithMany("Reservations")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelManageSys.API.Models.Room", "Room")
                        .WithMany("Reservations")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelManageSys.API.Models.Worker", "Worker")
                        .WithMany("Reservations")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Guest");

                    b.Navigation("Room");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("HotelManageSys.API.Models.ReservationAdditionalOffer", b =>
                {
                    b.HasOne("HotelManageSys.API.Models.AdditionalOffer", "AdditionalOffer")
                        .WithMany("ReservationAdditionalOffers")
                        .HasForeignKey("AdditionalOfferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelManageSys.API.Models.Reservation", "Reservation")
                        .WithMany("ReservationAdditionalOffers")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdditionalOffer");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("HotelManageSys.API.Models.Room", b =>
                {
                    b.HasOne("HotelManageSys.API.Models.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("HotelManageSys.API.Models.AdditionalOffer", b =>
                {
                    b.Navigation("ReservationAdditionalOffers");
                });

            modelBuilder.Entity("HotelManageSys.API.Models.Guest", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("HotelManageSys.API.Models.Reservation", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("ReservationAdditionalOffers");
                });

            modelBuilder.Entity("HotelManageSys.API.Models.Room", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("HotelManageSys.API.Models.RoomType", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("HotelManageSys.API.Models.Worker", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
